package Ovpnc::Model::DB;
use strict;
use warnings;
use Moose;
extends 'Catalyst::Model::DBIC::Schema';
with 'Catalyst::TraitFor::Model::DBIC::Schema::RequestConnectionPool';


=head1 NAME

Ovpnc::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Ovpnc>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Ovpnc::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head2 RequestConnectionPool

Two subs required for the above
will create persistant connection
per user/session

=cut

sub build_connect_key {
    my ($self, $c) = @_;
    return $c->sessionid;
}

sub build_connect_info {
    my ($self, $c) = @_;
    return $c->config->{'Model::DB'}->{connect_info};
}


=head1 AUTHOR

Nuriel Shem-Tov

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
