package Ovpnc::Model::DB;
use strict;
use File::Slurp;
use base 'Catalyst::Model::DBIC::Schema';
=comment
__PACKAGE__->config(
    schema_class => 'Ovpnc::Schema',

    connect_info => {
        dsn         => $ENV{OVPNC_DSN} ||= 'dbi:mysql:ovpnc',
        user        => $ENV{MYSQL_USER} ||= 'ovpnc',
        password    => ( $ENV{MYSQL_PASSFILE}
            ? read_file( $ENV{MYSQL_PASSFILE}, chomp => 1 )
            : read_file( 'config/.mysql', chomp => 1 )
        ),
        AutoCommit  => q{1},
    }
);

=cut

=head1 NAME

Ovpnc::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Ovpnc>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Ovpnc::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=cut


=head1 AUTHOR

Nuriel Shem-Tov

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
