package Ovpnc::Model::DB;
use strict;
use base 'Catalyst::Model::DBIC::Schema';

=head1 NAME

Ovpnc::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Ovpnc>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Ovpnc::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=cut


=head1 AUTHOR

Nuriel Shem-Tov

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
