#!/bin/bash
if [ ! -f .first_setup ]; then
    echo -e "Warning! This script will restore the ovpnc database.\nAll data will be lost. Break now (^c) if you wish to cancel."
else
    rm -rf .first_setup
fi
echo Enter mysql pass for $USER:
tm=$(stty -g)
stty -echo
read Passwd
stty $tm

PASSWD=$( echo $Passwd | sed 's/\\n//' )
MYPASS=$( openssl rand -hex 24 )
OVPNCUSER=`grep '"user".*:[\s +]".*"' ovpnc.json | sed 's/"user".*:.*"\(.*\)".*$/\1/' | sed 's/\s//g'`

mysql -p"$PASSWD" -u $USER <<QUERY_INPUT
drop database if exists ovpnc;
create database ovpnc;
grant all on ovpnc.* to "$OVPNCUSER"@'localhost' identified by "$MYPASS";
QUERY_INPUT

mysql -p"$PASSWD" $OVPNCUSER < config/ovpnc.sql
sed -i "s/\(^.*\"password\".*:.*\"\)\(.*\)\(\".*\)$/\1$MYPASS\3/" ovpnc.json
chown ovpnc.ovpnc ovpnc.json ovpnc.conf
chmod 400 ovpnc.json ovpnc.conf
