#!/bin/bash
if [ -z $1 ]; then
    echo Please provide the directory of the easy-rsa/2.0
    echo Example: $0 /usr/share/doc/openvpn/examples/easy-rsa/2.0
    exit 1
fi

rm -rf openvpn/conf/2.0
cp -r $1 openvpn/conf/
if [ -f openvpn/conf/2.0/openssl-1.0.0.cnf.gz ];then
    gunzip openvpn/conf/2.0/openssl-1.0.0.cnf.gz
fi
chmod o-rwx openvpn/conf/2.0/* -R
chown openvpn.ovpnc openvpn/conf/2.0 -R
chmod 770 openvpn/conf/2.0/
echo Directory copied successfully
if [ ! -f openvpn/conf/openvpn.conf.ovpnc ];then
    touch openvpn/conf/openvpn.conf.ovpnc
    chown ovpnc.ovpnc openvpn/conf/openvpn.conf.ovpnc
    chmod 600 openvpn/conf/openvpn.conf.ovpnc
fi
